// Team + league logo maps, shared by the nav Header and the /stories listing pages.
// Generated from ESPN team logos (public/logos/teams). Do not hand-edit; regenerate.

export const TEAM_LOGOS: Record<string, string> = {
  "Arizona Cardinals": "/logos/teams/nfl-arizona-cardinals.png",
  "Atlanta Falcons": "/logos/teams/nfl-atlanta-falcons.png",
  "Baltimore Ravens": "/logos/teams/nfl-baltimore-ravens.png",
  "Buffalo Bills": "/logos/teams/nfl-buffalo-bills.png",
  "Carolina Panthers": "/logos/teams/nfl-carolina-panthers.png",
  "Chicago Bears": "/logos/teams/nfl-chicago-bears.png",
  "Cincinnati Bengals": "/logos/teams/nfl-cincinnati-bengals.png",
  "Cleveland Browns": "/logos/teams/nfl-cleveland-browns.png",
  "Dallas Cowboys": "/logos/teams/nfl-dallas-cowboys.png",
  "Denver Broncos": "/logos/teams/nfl-denver-broncos.png",
  "Detroit Lions": "/logos/teams/nfl-detroit-lions.png",
  "Green Bay Packers": "/logos/teams/nfl-green-bay-packers.png",
  "Houston Texans": "/logos/teams/nfl-houston-texans.png",
  "Indianapolis Colts": "/logos/teams/nfl-indianapolis-colts.png",
  "Jacksonville Jaguars": "/logos/teams/nfl-jacksonville-jaguars.png",
  "Kansas City Chiefs": "/logos/teams/nfl-kansas-city-chiefs.png",
  "Las Vegas Raiders": "/logos/teams/nfl-las-vegas-raiders.png",
  "Los Angeles Chargers": "/logos/teams/nfl-los-angeles-chargers.png",
  "Los Angeles Rams": "/logos/teams/nfl-los-angeles-rams.png",
  "Miami Dolphins": "/logos/teams/nfl-miami-dolphins.png",
  "Minnesota Vikings": "/logos/teams/nfl-minnesota-vikings.png",
  "New England Patriots": "/logos/teams/nfl-new-england-patriots.png",
  "New Orleans Saints": "/logos/teams/nfl-new-orleans-saints.png",
  "New York Giants": "/logos/teams/nfl-new-york-giants.png",
  "New York Jets": "/logos/teams/nfl-new-york-jets.png",
  "Philadelphia Eagles": "/logos/teams/nfl-philadelphia-eagles.png",
  "Pittsburgh Steelers": "/logos/teams/nfl-pittsburgh-steelers.png",
  "San Francisco 49ers": "/logos/teams/nfl-san-francisco-49ers.png",
  "Seattle Seahawks": "/logos/teams/nfl-seattle-seahawks.png",
  "Tampa Bay Buccaneers": "/logos/teams/nfl-tampa-bay-buccaneers.png",
  "Tennessee Titans": "/logos/teams/nfl-tennessee-titans.png",
  "Washington Commanders": "/logos/teams/nfl-washington-commanders.png",
  "Atlanta Hawks": "/logos/teams/nba-atlanta-hawks.png",
  "Boston Celtics": "/logos/teams/nba-boston-celtics.png",
  "Brooklyn Nets": "/logos/teams/nba-brooklyn-nets.png",
  "Charlotte Hornets": "/logos/teams/nba-charlotte-hornets.png",
  "Chicago Bulls": "/logos/teams/nba-chicago-bulls.png",
  "Cleveland Cavaliers": "/logos/teams/nba-cleveland-cavaliers.png",
  "Dallas Mavericks": "/logos/teams/nba-dallas-mavericks.png",
  "Denver Nuggets": "/logos/teams/nba-denver-nuggets.png",
  "Detroit Pistons": "/logos/teams/nba-detroit-pistons.png",
  "Golden State Warriors": "/logos/teams/nba-golden-state-warriors.png",
  "Houston Rockets": "/logos/teams/nba-houston-rockets.png",
  "Indiana Pacers": "/logos/teams/nba-indiana-pacers.png",
  "LA Clippers": "/logos/teams/nba-la-clippers.png",
  "Los Angeles Lakers": "/logos/teams/nba-los-angeles-lakers.png",
  "Memphis Grizzlies": "/logos/teams/nba-memphis-grizzlies.png",
  "Miami Heat": "/logos/teams/nba-miami-heat.png",
  "Milwaukee Bucks": "/logos/teams/nba-milwaukee-bucks.png",
  "Minnesota Timberwolves": "/logos/teams/nba-minnesota-timberwolves.png",
  "New Orleans Pelicans": "/logos/teams/nba-new-orleans-pelicans.png",
  "New York Knicks": "/logos/teams/nba-new-york-knicks.png",
  "Oklahoma City Thunder": "/logos/teams/nba-oklahoma-city-thunder.png",
  "Orlando Magic": "/logos/teams/nba-orlando-magic.png",
  "Philadelphia 76ers": "/logos/teams/nba-philadelphia-76ers.png",
  "Phoenix Suns": "/logos/teams/nba-phoenix-suns.png",
  "Portland Trail Blazers": "/logos/teams/nba-portland-trail-blazers.png",
  "Sacramento Kings": "/logos/teams/nba-sacramento-kings.png",
  "San Antonio Spurs": "/logos/teams/nba-san-antonio-spurs.png",
  "Toronto Raptors": "/logos/teams/nba-toronto-raptors.png",
  "Utah Jazz": "/logos/teams/nba-utah-jazz.png",
  "Washington Wizards": "/logos/teams/nba-washington-wizards.png",
  "Arizona Diamondbacks": "/logos/teams/mlb-arizona-diamondbacks.png",
  "Atlanta Braves": "/logos/teams/mlb-atlanta-braves.png",
  "Baltimore Orioles": "/logos/teams/mlb-baltimore-orioles.png",
  "Boston Red Sox": "/logos/teams/mlb-boston-red-sox.png",
  "Chicago Cubs": "/logos/teams/mlb-chicago-cubs.png",
  "Chicago White Sox": "/logos/teams/mlb-chicago-white-sox.png",
  "Cincinnati Reds": "/logos/teams/mlb-cincinnati-reds.png",
  "Cleveland Guardians": "/logos/teams/mlb-cleveland-guardians.png",
  "Colorado Rockies": "/logos/teams/mlb-colorado-rockies.png",
  "Detroit Tigers": "/logos/teams/mlb-detroit-tigers.png",
  "Houston Astros": "/logos/teams/mlb-houston-astros.png",
  "Kansas City Royals": "/logos/teams/mlb-kansas-city-royals.png",
  "Los Angeles Angels": "/logos/teams/mlb-los-angeles-angels.png",
  "Los Angeles Dodgers": "/logos/teams/mlb-los-angeles-dodgers.png",
  "Miami Marlins": "/logos/teams/mlb-miami-marlins.png",
  "Milwaukee Brewers": "/logos/teams/mlb-milwaukee-brewers.png",
  "Minnesota Twins": "/logos/teams/mlb-minnesota-twins.png",
  "New York Mets": "/logos/teams/mlb-new-york-mets.png",
  "New York Yankees": "/logos/teams/mlb-new-york-yankees.png",
  "Athletics": "/logos/teams/mlb-oakland-athletics.png",
  "Philadelphia Phillies": "/logos/teams/mlb-philadelphia-phillies.png",
  "Pittsburgh Pirates": "/logos/teams/mlb-pittsburgh-pirates.png",
  "San Diego Padres": "/logos/teams/mlb-san-diego-padres.png",
  "San Francisco Giants": "/logos/teams/mlb-san-francisco-giants.png",
  "Seattle Mariners": "/logos/teams/mlb-seattle-mariners.png",
  "St. Louis Cardinals": "/logos/teams/mlb-st-louis-cardinals.png",
  "Tampa Bay Rays": "/logos/teams/mlb-tampa-bay-rays.png",
  "Texas Rangers": "/logos/teams/mlb-texas-rangers.png",
  "Toronto Blue Jays": "/logos/teams/mlb-toronto-blue-jays.png",
  "Washington Nationals": "/logos/teams/mlb-washington-nationals.png",
  "Anaheim Ducks": "/logos/teams/nhl-anaheim-ducks.png",
  "Boston Bruins": "/logos/teams/nhl-boston-bruins.png",
  "Buffalo Sabres": "/logos/teams/nhl-buffalo-sabres.png",
  "Calgary Flames": "/logos/teams/nhl-calgary-flames.png",
  "Carolina Hurricanes": "/logos/teams/nhl-carolina-hurricanes.png",
  "Chicago Blackhawks": "/logos/teams/nhl-chicago-blackhawks.png",
  "Colorado Avalanche": "/logos/teams/nhl-colorado-avalanche.png",
  "Columbus Blue Jackets": "/logos/teams/nhl-columbus-blue-jackets.png",
  "Dallas Stars": "/logos/teams/nhl-dallas-stars.png",
  "Detroit Red Wings": "/logos/teams/nhl-detroit-red-wings.png",
  "Edmonton Oilers": "/logos/teams/nhl-edmonton-oilers.png",
  "Florida Panthers": "/logos/teams/nhl-florida-panthers.png",
  "Los Angeles Kings": "/logos/teams/nhl-los-angeles-kings.png",
  "Minnesota Wild": "/logos/teams/nhl-minnesota-wild.png",
  "Montreal Canadiens": "/logos/teams/nhl-montreal-canadiens.png",
  "Nashville Predators": "/logos/teams/nhl-nashville-predators.png",
  "New Jersey Devils": "/logos/teams/nhl-new-jersey-devils.png",
  "New York Islanders": "/logos/teams/nhl-new-york-islanders.png",
  "New York Rangers": "/logos/teams/nhl-new-york-rangers.png",
  "Ottawa Senators": "/logos/teams/nhl-ottawa-senators.png",
  "Philadelphia Flyers": "/logos/teams/nhl-philadelphia-flyers.png",
  "Pittsburgh Penguins": "/logos/teams/nhl-pittsburgh-penguins.png",
  "San Jose Sharks": "/logos/teams/nhl-san-jose-sharks.png",
  "Seattle Kraken": "/logos/teams/nhl-seattle-kraken.png",
  "St. Louis Blues": "/logos/teams/nhl-st-louis-blues.png",
  "Tampa Bay Lightning": "/logos/teams/nhl-tampa-bay-lightning.png",
  "Toronto Maple Leafs": "/logos/teams/nhl-toronto-maple-leafs.png",
  "Utah Mammoth": "/logos/teams/nhl-utah-mammoth.png",
  "Vancouver Canucks": "/logos/teams/nhl-vancouver-canucks.png",
  "Vegas Golden Knights": "/logos/teams/nhl-vegas-golden-knights.png",
  "Washington Capitals": "/logos/teams/nhl-washington-capitals.png",
  "Winnipeg Jets": "/logos/teams/nhl-winnipeg-jets.png",

  // Premier League clubs. Added 2026-09-04: every soccer post was league "soccer"
  // with an empty teams array, so /stories?team=premier-league (which the nav has
  // always linked to) returned nothing and no club had a page of its own.
  "Arsenal": "/logos/teams/epl-arsenal.png",
  "Aston Villa": "/logos/teams/epl-aston-villa.png",
  "Bournemouth": "/logos/teams/epl-bournemouth.png",
  "Brentford": "/logos/teams/epl-brentford.png",
  "Brighton": "/logos/teams/epl-brighton.png",
  "Chelsea": "/logos/teams/epl-chelsea.png",
  "Coventry City": "/logos/teams/epl-coventry-city.png",
  "Crystal Palace": "/logos/teams/epl-crystal-palace.png",
  "Everton": "/logos/teams/epl-everton.png",
  "Fulham": "/logos/teams/epl-fulham.png",
  "Hull City": "/logos/teams/epl-hull-city.png",
  "Ipswich Town": "/logos/teams/epl-ipswich-town.png",
  "Leeds United": "/logos/teams/epl-leeds-united.png",
  "Liverpool": "/logos/teams/epl-liverpool.png",
  "Manchester City": "/logos/teams/epl-manchester-city.png",
  "Manchester United": "/logos/teams/epl-manchester-united.png",
  "Newcastle": "/logos/teams/epl-newcastle.png",
  "Nottingham Forest": "/logos/teams/epl-nottingham-forest.png",
  "Sunderland": "/logos/teams/epl-sunderland.png",
  "Tottenham": "/logos/teams/epl-tottenham.png",

  // College football (FBS) schools with a uniform schedule post. Added 2026-09-26:
  // all ~95 school posts shipped with an empty teams array, so no school had a
  // page and College sat under "More". Names are ESPN's "School Nickname" form
  // (Cal, Pitt, Hawaii and Appalachian State match our post titles instead), which
  // keeps Miami (FL) clear of Miami (OH) and every school clear of the pro clubs.
  // Logos: ESPN ncaa/500 marks, resized to 128px.
  "Air Force Falcons": "/logos/teams/ncaa-air-force-falcons.png",
  "Alabama Crimson Tide": "/logos/teams/ncaa-alabama-crimson-tide.png",
  "Appalachian State Mountaineers": "/logos/teams/ncaa-appalachian-state-mountaineers.png",
  "Arizona State Sun Devils": "/logos/teams/ncaa-arizona-state-sun-devils.png",
  "Arizona Wildcats": "/logos/teams/ncaa-arizona-wildcats.png",
  "Arkansas Razorbacks": "/logos/teams/ncaa-arkansas-razorbacks.png",
  "Army Black Knights": "/logos/teams/ncaa-army-black-knights.png",
  "Auburn Tigers": "/logos/teams/ncaa-auburn-tigers.png",
  "BYU Cougars": "/logos/teams/ncaa-byu-cougars.png",
  "Baylor Bears": "/logos/teams/ncaa-baylor-bears.png",
  "Boise State Broncos": "/logos/teams/ncaa-boise-state-broncos.png",
  "Boston College Eagles": "/logos/teams/ncaa-boston-college-eagles.png",
  "Buffalo Bulls": "/logos/teams/ncaa-buffalo-bulls.png",
  "Cal Golden Bears": "/logos/teams/ncaa-cal-golden-bears.png",
  "Cincinnati Bearcats": "/logos/teams/ncaa-cincinnati-bearcats.png",
  "Clemson Tigers": "/logos/teams/ncaa-clemson-tigers.png",
  "Coastal Carolina Chanticleers": "/logos/teams/ncaa-coastal-carolina-chanticleers.png",
  "Colorado Buffaloes": "/logos/teams/ncaa-colorado-buffaloes.png",
  "Colorado State Rams": "/logos/teams/ncaa-colorado-state-rams.png",
  "Duke Blue Devils": "/logos/teams/ncaa-duke-blue-devils.png",
  "East Carolina Pirates": "/logos/teams/ncaa-east-carolina-pirates.png",
  "Florida Gators": "/logos/teams/ncaa-florida-gators.png",
  "Florida State Seminoles": "/logos/teams/ncaa-florida-state-seminoles.png",
  "Fresno State Bulldogs": "/logos/teams/ncaa-fresno-state-bulldogs.png",
  "Georgia Bulldogs": "/logos/teams/ncaa-georgia-bulldogs.png",
  "Georgia Tech Yellow Jackets": "/logos/teams/ncaa-georgia-tech-yellow-jackets.png",
  "Hawaii Rainbow Warriors": "/logos/teams/ncaa-hawaii-rainbow-warriors.png",
  "Houston Cougars": "/logos/teams/ncaa-houston-cougars.png",
  "Illinois Fighting Illini": "/logos/teams/ncaa-illinois-fighting-illini.png",
  "Indiana Hoosiers": "/logos/teams/ncaa-indiana-hoosiers.png",
  "Iowa Hawkeyes": "/logos/teams/ncaa-iowa-hawkeyes.png",
  "Iowa State Cyclones": "/logos/teams/ncaa-iowa-state-cyclones.png",
  "James Madison Dukes": "/logos/teams/ncaa-james-madison-dukes.png",
  "Kansas Jayhawks": "/logos/teams/ncaa-kansas-jayhawks.png",
  "Kansas State Wildcats": "/logos/teams/ncaa-kansas-state-wildcats.png",
  "Kentucky Wildcats": "/logos/teams/ncaa-kentucky-wildcats.png",
  "LSU Tigers": "/logos/teams/ncaa-lsu-tigers.png",
  "Liberty Flames": "/logos/teams/ncaa-liberty-flames.png",
  "Louisville Cardinals": "/logos/teams/ncaa-louisville-cardinals.png",
  "Marshall Thundering Herd": "/logos/teams/ncaa-marshall-thundering-herd.png",
  "Maryland Terrapins": "/logos/teams/ncaa-maryland-terrapins.png",
  "Memphis Tigers": "/logos/teams/ncaa-memphis-tigers.png",
  "Miami Hurricanes": "/logos/teams/ncaa-miami-hurricanes.png",
  "Michigan State Spartans": "/logos/teams/ncaa-michigan-state-spartans.png",
  "Michigan Wolverines": "/logos/teams/ncaa-michigan-wolverines.png",
  "Minnesota Golden Gophers": "/logos/teams/ncaa-minnesota-golden-gophers.png",
  "Mississippi State Bulldogs": "/logos/teams/ncaa-mississippi-state-bulldogs.png",
  "Missouri Tigers": "/logos/teams/ncaa-missouri-tigers.png",
  "NC State Wolfpack": "/logos/teams/ncaa-nc-state-wolfpack.png",
  "Navy Midshipmen": "/logos/teams/ncaa-navy-midshipmen.png",
  "Nebraska Cornhuskers": "/logos/teams/ncaa-nebraska-cornhuskers.png",
  "North Carolina Tar Heels": "/logos/teams/ncaa-north-carolina-tar-heels.png",
  "North Texas Mean Green": "/logos/teams/ncaa-north-texas-mean-green.png",
  "Northwestern Wildcats": "/logos/teams/ncaa-northwestern-wildcats.png",
  "Notre Dame Fighting Irish": "/logos/teams/ncaa-notre-dame-fighting-irish.png",
  "Ohio State Buckeyes": "/logos/teams/ncaa-ohio-state-buckeyes.png",
  "Oklahoma Sooners": "/logos/teams/ncaa-oklahoma-sooners.png",
  "Oklahoma State Cowboys": "/logos/teams/ncaa-oklahoma-state-cowboys.png",
  "Ole Miss Rebels": "/logos/teams/ncaa-ole-miss-rebels.png",
  "Oregon Ducks": "/logos/teams/ncaa-oregon-ducks.png",
  "Oregon State Beavers": "/logos/teams/ncaa-oregon-state-beavers.png",
  "Penn State Nittany Lions": "/logos/teams/ncaa-penn-state-nittany-lions.png",
  "Pitt Panthers": "/logos/teams/ncaa-pitt-panthers.png",
  "Purdue Boilermakers": "/logos/teams/ncaa-purdue-boilermakers.png",
  "Rutgers Scarlet Knights": "/logos/teams/ncaa-rutgers-scarlet-knights.png",
  "SMU Mustangs": "/logos/teams/ncaa-smu-mustangs.png",
  "San Diego State Aztecs": "/logos/teams/ncaa-san-diego-state-aztecs.png",
  "South Carolina Gamecocks": "/logos/teams/ncaa-south-carolina-gamecocks.png",
  "South Florida Bulls": "/logos/teams/ncaa-south-florida-bulls.png",
  "Stanford Cardinal": "/logos/teams/ncaa-stanford-cardinal.png",
  "Syracuse Orange": "/logos/teams/ncaa-syracuse-orange.png",
  "TCU Horned Frogs": "/logos/teams/ncaa-tcu-horned-frogs.png",
  "Temple Owls": "/logos/teams/ncaa-temple-owls.png",
  "Rice Owls": "/logos/teams/ncaa-rice-owls.png",
  "UTSA Roadrunners": "/logos/teams/ncaa-utsa-roadrunners.png",
  "Texas State Bobcats": "/logos/teams/ncaa-texas-state-bobcats.png",
  "Georgia Southern Eagles": "/logos/teams/ncaa-georgia-southern-eagles.png",
  "Tennessee Volunteers": "/logos/teams/ncaa-tennessee-volunteers.png",
  "Texas A&M Aggies": "/logos/teams/ncaa-texas-am-aggies.png",
  "Texas Longhorns": "/logos/teams/ncaa-texas-longhorns.png",
  "Texas Tech Red Raiders": "/logos/teams/ncaa-texas-tech-red-raiders.png",
  "Toledo Rockets": "/logos/teams/ncaa-toledo-rockets.png",
  "Tulane Green Wave": "/logos/teams/ncaa-tulane-green-wave.png",
  "Tulsa Golden Hurricane": "/logos/teams/ncaa-tulsa-golden-hurricane.png",
  "UCF Knights": "/logos/teams/ncaa-ucf-knights.png",
  "UCLA Bruins": "/logos/teams/ncaa-ucla-bruins.png",
  "UConn Huskies": "/logos/teams/ncaa-uconn-huskies.png",
  "UNLV Rebels": "/logos/teams/ncaa-unlv-rebels.png",
  "USC Trojans": "/logos/teams/ncaa-usc-trojans.png",
  "Utah State Aggies": "/logos/teams/ncaa-utah-state-aggies.png",
  "Utah Utes": "/logos/teams/ncaa-utah-utes.png",
  "Vanderbilt Commodores": "/logos/teams/ncaa-vanderbilt-commodores.png",
  "Virginia Cavaliers": "/logos/teams/ncaa-virginia-cavaliers.png",
  "Virginia Tech Hokies": "/logos/teams/ncaa-virginia-tech-hokies.png",
  "Wake Forest Demon Deacons": "/logos/teams/ncaa-wake-forest-demon-deacons.png",
  "Washington Huskies": "/logos/teams/ncaa-washington-huskies.png",
  "Washington State Cougars": "/logos/teams/ncaa-washington-state-cougars.png",
  "West Virginia Mountaineers": "/logos/teams/ncaa-west-virginia-mountaineers.png",
  "Wisconsin Badgers": "/logos/teams/ncaa-wisconsin-badgers.png",
};

// Keyed by the URL slug the nav builds (name.toLowerCase().replace(/\\s+/g, '-')),
// so the /stories?team=<slug> page can look a logo up from the query param.
export const TEAM_LOGO_BY_SLUG: Record<string, string> = {
  // Soccer competitions + F1 constructors — filter-page logos for /stories?team=<slug>.
  // The nav shows these via COMPETITION_LOGOS (by display name); this maps the slug the
  // nav builds so the filter heading gets the same logo. Assets in /logos/leagues/.
  "international-competitions": "/logos/leagues/international-globe.svg",
  "uefa-champions-league": "/logos/leagues/soccer-uefa-champions-league.png",
  "premier-league": "/logos/leagues/soccer-premier-league.png",
  "la-liga": "/logos/leagues/soccer-la-liga.png",
  "serie-a": "/logos/leagues/soccer-serie-a.png",
  "bundesliga": "/logos/leagues/soccer-bundesliga.png",
  "ligue-1": "/logos/leagues/soccer-ligue-1.png",
  "mls": "/logos/leagues/soccer-mls.png",
  "alpine": "/logos/leagues/racing-alpine.png",
  "aston-martin": "/logos/leagues/racing-aston-martin.png",
  "audi": "/logos/leagues/racing-audi.png",
  "cadillac": "/logos/leagues/racing-cadillac.png",
  "ferrari": "/logos/leagues/racing-ferrari.png",
  "haas": "/logos/leagues/racing-haas.png",
  "mclaren": "/logos/leagues/racing-mclaren.png",
  "mercedes": "/logos/leagues/racing-mercedes.png",
  "racing-bulls": "/logos/leagues/racing-racing-bulls.png",
  "red-bull-racing": "/logos/leagues/racing-red-bull-racing.png",
  "williams": "/logos/leagues/racing-williams.png",
  "arizona-cardinals": "/logos/teams/nfl-arizona-cardinals.png",
  "atlanta-falcons": "/logos/teams/nfl-atlanta-falcons.png",
  "baltimore-ravens": "/logos/teams/nfl-baltimore-ravens.png",
  "buffalo-bills": "/logos/teams/nfl-buffalo-bills.png",
  "carolina-panthers": "/logos/teams/nfl-carolina-panthers.png",
  "chicago-bears": "/logos/teams/nfl-chicago-bears.png",
  "cincinnati-bengals": "/logos/teams/nfl-cincinnati-bengals.png",
  "cleveland-browns": "/logos/teams/nfl-cleveland-browns.png",
  "dallas-cowboys": "/logos/teams/nfl-dallas-cowboys.png",
  "denver-broncos": "/logos/teams/nfl-denver-broncos.png",
  "detroit-lions": "/logos/teams/nfl-detroit-lions.png",
  "green-bay-packers": "/logos/teams/nfl-green-bay-packers.png",
  "houston-texans": "/logos/teams/nfl-houston-texans.png",
  "indianapolis-colts": "/logos/teams/nfl-indianapolis-colts.png",
  "jacksonville-jaguars": "/logos/teams/nfl-jacksonville-jaguars.png",
  "kansas-city-chiefs": "/logos/teams/nfl-kansas-city-chiefs.png",
  "las-vegas-raiders": "/logos/teams/nfl-las-vegas-raiders.png",
  "los-angeles-chargers": "/logos/teams/nfl-los-angeles-chargers.png",
  "los-angeles-rams": "/logos/teams/nfl-los-angeles-rams.png",
  "miami-dolphins": "/logos/teams/nfl-miami-dolphins.png",
  "minnesota-vikings": "/logos/teams/nfl-minnesota-vikings.png",
  "new-england-patriots": "/logos/teams/nfl-new-england-patriots.png",
  "new-orleans-saints": "/logos/teams/nfl-new-orleans-saints.png",
  "new-york-giants": "/logos/teams/nfl-new-york-giants.png",
  "new-york-jets": "/logos/teams/nfl-new-york-jets.png",
  "philadelphia-eagles": "/logos/teams/nfl-philadelphia-eagles.png",
  "pittsburgh-steelers": "/logos/teams/nfl-pittsburgh-steelers.png",
  "san-francisco-49ers": "/logos/teams/nfl-san-francisco-49ers.png",
  "seattle-seahawks": "/logos/teams/nfl-seattle-seahawks.png",
  "tampa-bay-buccaneers": "/logos/teams/nfl-tampa-bay-buccaneers.png",
  "tennessee-titans": "/logos/teams/nfl-tennessee-titans.png",
  "washington-commanders": "/logos/teams/nfl-washington-commanders.png",
  "atlanta-hawks": "/logos/teams/nba-atlanta-hawks.png",
  "boston-celtics": "/logos/teams/nba-boston-celtics.png",
  "brooklyn-nets": "/logos/teams/nba-brooklyn-nets.png",
  "charlotte-hornets": "/logos/teams/nba-charlotte-hornets.png",
  "chicago-bulls": "/logos/teams/nba-chicago-bulls.png",
  "cleveland-cavaliers": "/logos/teams/nba-cleveland-cavaliers.png",
  "dallas-mavericks": "/logos/teams/nba-dallas-mavericks.png",
  "denver-nuggets": "/logos/teams/nba-denver-nuggets.png",
  "detroit-pistons": "/logos/teams/nba-detroit-pistons.png",
  "golden-state-warriors": "/logos/teams/nba-golden-state-warriors.png",
  "houston-rockets": "/logos/teams/nba-houston-rockets.png",
  "indiana-pacers": "/logos/teams/nba-indiana-pacers.png",
  "la-clippers": "/logos/teams/nba-la-clippers.png",
  "los-angeles-lakers": "/logos/teams/nba-los-angeles-lakers.png",
  "memphis-grizzlies": "/logos/teams/nba-memphis-grizzlies.png",
  "miami-heat": "/logos/teams/nba-miami-heat.png",
  "milwaukee-bucks": "/logos/teams/nba-milwaukee-bucks.png",
  "minnesota-timberwolves": "/logos/teams/nba-minnesota-timberwolves.png",
  "new-orleans-pelicans": "/logos/teams/nba-new-orleans-pelicans.png",
  "new-york-knicks": "/logos/teams/nba-new-york-knicks.png",
  "oklahoma-city-thunder": "/logos/teams/nba-oklahoma-city-thunder.png",
  "orlando-magic": "/logos/teams/nba-orlando-magic.png",
  "philadelphia-76ers": "/logos/teams/nba-philadelphia-76ers.png",
  "phoenix-suns": "/logos/teams/nba-phoenix-suns.png",
  "portland-trail-blazers": "/logos/teams/nba-portland-trail-blazers.png",
  "sacramento-kings": "/logos/teams/nba-sacramento-kings.png",
  "san-antonio-spurs": "/logos/teams/nba-san-antonio-spurs.png",
  "toronto-raptors": "/logos/teams/nba-toronto-raptors.png",
  "utah-jazz": "/logos/teams/nba-utah-jazz.png",
  "washington-wizards": "/logos/teams/nba-washington-wizards.png",
  "arizona-diamondbacks": "/logos/teams/mlb-arizona-diamondbacks.png",
  "atlanta-braves": "/logos/teams/mlb-atlanta-braves.png",
  "baltimore-orioles": "/logos/teams/mlb-baltimore-orioles.png",
  "boston-red-sox": "/logos/teams/mlb-boston-red-sox.png",
  "chicago-cubs": "/logos/teams/mlb-chicago-cubs.png",
  "chicago-white-sox": "/logos/teams/mlb-chicago-white-sox.png",
  "cincinnati-reds": "/logos/teams/mlb-cincinnati-reds.png",
  "cleveland-guardians": "/logos/teams/mlb-cleveland-guardians.png",
  "colorado-rockies": "/logos/teams/mlb-colorado-rockies.png",
  "detroit-tigers": "/logos/teams/mlb-detroit-tigers.png",
  "houston-astros": "/logos/teams/mlb-houston-astros.png",
  "kansas-city-royals": "/logos/teams/mlb-kansas-city-royals.png",
  "los-angeles-angels": "/logos/teams/mlb-los-angeles-angels.png",
  "los-angeles-dodgers": "/logos/teams/mlb-los-angeles-dodgers.png",
  "miami-marlins": "/logos/teams/mlb-miami-marlins.png",
  "milwaukee-brewers": "/logos/teams/mlb-milwaukee-brewers.png",
  "minnesota-twins": "/logos/teams/mlb-minnesota-twins.png",
  "new-york-mets": "/logos/teams/mlb-new-york-mets.png",
  "new-york-yankees": "/logos/teams/mlb-new-york-yankees.png",
  "athletics": "/logos/teams/mlb-oakland-athletics.png",
  // Legacy slug: kept so older "oakland-athletics" links still resolve a logo.
  "oakland-athletics": "/logos/teams/mlb-oakland-athletics.png",
  "philadelphia-phillies": "/logos/teams/mlb-philadelphia-phillies.png",
  "pittsburgh-pirates": "/logos/teams/mlb-pittsburgh-pirates.png",
  "san-diego-padres": "/logos/teams/mlb-san-diego-padres.png",
  "san-francisco-giants": "/logos/teams/mlb-san-francisco-giants.png",
  "seattle-mariners": "/logos/teams/mlb-seattle-mariners.png",
  "st-louis-cardinals": "/logos/teams/mlb-st-louis-cardinals.png",
  "tampa-bay-rays": "/logos/teams/mlb-tampa-bay-rays.png",
  "texas-rangers": "/logos/teams/mlb-texas-rangers.png",
  "toronto-blue-jays": "/logos/teams/mlb-toronto-blue-jays.png",
  "washington-nationals": "/logos/teams/mlb-washington-nationals.png",
  "anaheim-ducks": "/logos/teams/nhl-anaheim-ducks.png",
  "boston-bruins": "/logos/teams/nhl-boston-bruins.png",
  "buffalo-sabres": "/logos/teams/nhl-buffalo-sabres.png",
  "calgary-flames": "/logos/teams/nhl-calgary-flames.png",
  "carolina-hurricanes": "/logos/teams/nhl-carolina-hurricanes.png",
  "chicago-blackhawks": "/logos/teams/nhl-chicago-blackhawks.png",
  "colorado-avalanche": "/logos/teams/nhl-colorado-avalanche.png",
  "columbus-blue-jackets": "/logos/teams/nhl-columbus-blue-jackets.png",
  "dallas-stars": "/logos/teams/nhl-dallas-stars.png",
  "detroit-red-wings": "/logos/teams/nhl-detroit-red-wings.png",
  "edmonton-oilers": "/logos/teams/nhl-edmonton-oilers.png",
  "florida-panthers": "/logos/teams/nhl-florida-panthers.png",
  "los-angeles-kings": "/logos/teams/nhl-los-angeles-kings.png",
  "minnesota-wild": "/logos/teams/nhl-minnesota-wild.png",
  "montreal-canadiens": "/logos/teams/nhl-montreal-canadiens.png",
  "nashville-predators": "/logos/teams/nhl-nashville-predators.png",
  "new-jersey-devils": "/logos/teams/nhl-new-jersey-devils.png",
  "new-york-islanders": "/logos/teams/nhl-new-york-islanders.png",
  "new-york-rangers": "/logos/teams/nhl-new-york-rangers.png",
  "ottawa-senators": "/logos/teams/nhl-ottawa-senators.png",
  "philadelphia-flyers": "/logos/teams/nhl-philadelphia-flyers.png",
  "pittsburgh-penguins": "/logos/teams/nhl-pittsburgh-penguins.png",
  "san-jose-sharks": "/logos/teams/nhl-san-jose-sharks.png",
  "seattle-kraken": "/logos/teams/nhl-seattle-kraken.png",
  "st-louis-blues": "/logos/teams/nhl-st-louis-blues.png",
  "tampa-bay-lightning": "/logos/teams/nhl-tampa-bay-lightning.png",
  "toronto-maple-leafs": "/logos/teams/nhl-toronto-maple-leafs.png",
  "utah-mammoth": "/logos/teams/nhl-utah-mammoth.png",
  // Legacy slug from the club's naming-rights year, kept so old links resolve a logo.
  "utah-hockey-club": "/logos/teams/nhl-utah-mammoth.png",
  "vancouver-canucks": "/logos/teams/nhl-vancouver-canucks.png",
  "vegas-golden-knights": "/logos/teams/nhl-vegas-golden-knights.png",
  "washington-capitals": "/logos/teams/nhl-washington-capitals.png",
  "winnipeg-jets": "/logos/teams/nhl-winnipeg-jets.png",

  // Premier League clubs (see the note in TEAM_LOGOS).
  "arsenal": "/logos/teams/epl-arsenal.png",
  "aston-villa": "/logos/teams/epl-aston-villa.png",
  "bournemouth": "/logos/teams/epl-bournemouth.png",
  "brentford": "/logos/teams/epl-brentford.png",
  "brighton": "/logos/teams/epl-brighton.png",
  "chelsea": "/logos/teams/epl-chelsea.png",
  "coventry-city": "/logos/teams/epl-coventry-city.png",
  "crystal-palace": "/logos/teams/epl-crystal-palace.png",
  "everton": "/logos/teams/epl-everton.png",
  "fulham": "/logos/teams/epl-fulham.png",
  "hull-city": "/logos/teams/epl-hull-city.png",
  "ipswich-town": "/logos/teams/epl-ipswich-town.png",
  "leeds-united": "/logos/teams/epl-leeds-united.png",
  "liverpool": "/logos/teams/epl-liverpool.png",
  "manchester-city": "/logos/teams/epl-manchester-city.png",
  "manchester-united": "/logos/teams/epl-manchester-united.png",
  "newcastle": "/logos/teams/epl-newcastle.png",
  "nottingham-forest": "/logos/teams/epl-nottingham-forest.png",
  "sunderland": "/logos/teams/epl-sunderland.png",
  "tottenham": "/logos/teams/epl-tottenham.png",

  // College football schools (see the note in TEAM_LOGOS).
  "air-force-falcons": "/logos/teams/ncaa-air-force-falcons.png",
  "alabama-crimson-tide": "/logos/teams/ncaa-alabama-crimson-tide.png",
  "appalachian-state-mountaineers": "/logos/teams/ncaa-appalachian-state-mountaineers.png",
  "arizona-state-sun-devils": "/logos/teams/ncaa-arizona-state-sun-devils.png",
  "arizona-wildcats": "/logos/teams/ncaa-arizona-wildcats.png",
  "arkansas-razorbacks": "/logos/teams/ncaa-arkansas-razorbacks.png",
  "army-black-knights": "/logos/teams/ncaa-army-black-knights.png",
  "auburn-tigers": "/logos/teams/ncaa-auburn-tigers.png",
  "byu-cougars": "/logos/teams/ncaa-byu-cougars.png",
  "baylor-bears": "/logos/teams/ncaa-baylor-bears.png",
  "boise-state-broncos": "/logos/teams/ncaa-boise-state-broncos.png",
  "boston-college-eagles": "/logos/teams/ncaa-boston-college-eagles.png",
  "buffalo-bulls": "/logos/teams/ncaa-buffalo-bulls.png",
  "cal-golden-bears": "/logos/teams/ncaa-cal-golden-bears.png",
  "cincinnati-bearcats": "/logos/teams/ncaa-cincinnati-bearcats.png",
  "clemson-tigers": "/logos/teams/ncaa-clemson-tigers.png",
  "coastal-carolina-chanticleers": "/logos/teams/ncaa-coastal-carolina-chanticleers.png",
  "colorado-buffaloes": "/logos/teams/ncaa-colorado-buffaloes.png",
  "colorado-state-rams": "/logos/teams/ncaa-colorado-state-rams.png",
  "duke-blue-devils": "/logos/teams/ncaa-duke-blue-devils.png",
  "east-carolina-pirates": "/logos/teams/ncaa-east-carolina-pirates.png",
  "florida-gators": "/logos/teams/ncaa-florida-gators.png",
  "florida-state-seminoles": "/logos/teams/ncaa-florida-state-seminoles.png",
  "fresno-state-bulldogs": "/logos/teams/ncaa-fresno-state-bulldogs.png",
  "georgia-bulldogs": "/logos/teams/ncaa-georgia-bulldogs.png",
  "georgia-tech-yellow-jackets": "/logos/teams/ncaa-georgia-tech-yellow-jackets.png",
  "hawaii-rainbow-warriors": "/logos/teams/ncaa-hawaii-rainbow-warriors.png",
  "houston-cougars": "/logos/teams/ncaa-houston-cougars.png",
  "illinois-fighting-illini": "/logos/teams/ncaa-illinois-fighting-illini.png",
  "indiana-hoosiers": "/logos/teams/ncaa-indiana-hoosiers.png",
  "iowa-hawkeyes": "/logos/teams/ncaa-iowa-hawkeyes.png",
  "iowa-state-cyclones": "/logos/teams/ncaa-iowa-state-cyclones.png",
  "james-madison-dukes": "/logos/teams/ncaa-james-madison-dukes.png",
  "kansas-jayhawks": "/logos/teams/ncaa-kansas-jayhawks.png",
  "kansas-state-wildcats": "/logos/teams/ncaa-kansas-state-wildcats.png",
  "kentucky-wildcats": "/logos/teams/ncaa-kentucky-wildcats.png",
  "lsu-tigers": "/logos/teams/ncaa-lsu-tigers.png",
  "liberty-flames": "/logos/teams/ncaa-liberty-flames.png",
  "louisville-cardinals": "/logos/teams/ncaa-louisville-cardinals.png",
  "marshall-thundering-herd": "/logos/teams/ncaa-marshall-thundering-herd.png",
  "maryland-terrapins": "/logos/teams/ncaa-maryland-terrapins.png",
  "memphis-tigers": "/logos/teams/ncaa-memphis-tigers.png",
  "miami-hurricanes": "/logos/teams/ncaa-miami-hurricanes.png",
  "michigan-state-spartans": "/logos/teams/ncaa-michigan-state-spartans.png",
  "michigan-wolverines": "/logos/teams/ncaa-michigan-wolverines.png",
  "minnesota-golden-gophers": "/logos/teams/ncaa-minnesota-golden-gophers.png",
  "mississippi-state-bulldogs": "/logos/teams/ncaa-mississippi-state-bulldogs.png",
  "missouri-tigers": "/logos/teams/ncaa-missouri-tigers.png",
  "nc-state-wolfpack": "/logos/teams/ncaa-nc-state-wolfpack.png",
  "navy-midshipmen": "/logos/teams/ncaa-navy-midshipmen.png",
  "nebraska-cornhuskers": "/logos/teams/ncaa-nebraska-cornhuskers.png",
  "north-carolina-tar-heels": "/logos/teams/ncaa-north-carolina-tar-heels.png",
  "north-texas-mean-green": "/logos/teams/ncaa-north-texas-mean-green.png",
  "northwestern-wildcats": "/logos/teams/ncaa-northwestern-wildcats.png",
  "notre-dame-fighting-irish": "/logos/teams/ncaa-notre-dame-fighting-irish.png",
  "ohio-state-buckeyes": "/logos/teams/ncaa-ohio-state-buckeyes.png",
  "oklahoma-sooners": "/logos/teams/ncaa-oklahoma-sooners.png",
  "oklahoma-state-cowboys": "/logos/teams/ncaa-oklahoma-state-cowboys.png",
  "ole-miss-rebels": "/logos/teams/ncaa-ole-miss-rebels.png",
  "oregon-ducks": "/logos/teams/ncaa-oregon-ducks.png",
  "oregon-state-beavers": "/logos/teams/ncaa-oregon-state-beavers.png",
  "penn-state-nittany-lions": "/logos/teams/ncaa-penn-state-nittany-lions.png",
  "pitt-panthers": "/logos/teams/ncaa-pitt-panthers.png",
  "purdue-boilermakers": "/logos/teams/ncaa-purdue-boilermakers.png",
  "rutgers-scarlet-knights": "/logos/teams/ncaa-rutgers-scarlet-knights.png",
  "smu-mustangs": "/logos/teams/ncaa-smu-mustangs.png",
  "san-diego-state-aztecs": "/logos/teams/ncaa-san-diego-state-aztecs.png",
  "south-carolina-gamecocks": "/logos/teams/ncaa-south-carolina-gamecocks.png",
  "south-florida-bulls": "/logos/teams/ncaa-south-florida-bulls.png",
  "stanford-cardinal": "/logos/teams/ncaa-stanford-cardinal.png",
  "syracuse-orange": "/logos/teams/ncaa-syracuse-orange.png",
  "tcu-horned-frogs": "/logos/teams/ncaa-tcu-horned-frogs.png",
  "temple-owls": "/logos/teams/ncaa-temple-owls.png",
  "rice-owls": "/logos/teams/ncaa-rice-owls.png",
  "utsa-roadrunners": "/logos/teams/ncaa-utsa-roadrunners.png",
  "texas-state-bobcats": "/logos/teams/ncaa-texas-state-bobcats.png",
  "georgia-southern-eagles": "/logos/teams/ncaa-georgia-southern-eagles.png",
  "tennessee-volunteers": "/logos/teams/ncaa-tennessee-volunteers.png",
  "texas-am-aggies": "/logos/teams/ncaa-texas-am-aggies.png",
  "texas-longhorns": "/logos/teams/ncaa-texas-longhorns.png",
  "texas-tech-red-raiders": "/logos/teams/ncaa-texas-tech-red-raiders.png",
  "toledo-rockets": "/logos/teams/ncaa-toledo-rockets.png",
  "tulane-green-wave": "/logos/teams/ncaa-tulane-green-wave.png",
  "tulsa-golden-hurricane": "/logos/teams/ncaa-tulsa-golden-hurricane.png",
  "ucf-knights": "/logos/teams/ncaa-ucf-knights.png",
  "ucla-bruins": "/logos/teams/ncaa-ucla-bruins.png",
  "uconn-huskies": "/logos/teams/ncaa-uconn-huskies.png",
  "unlv-rebels": "/logos/teams/ncaa-unlv-rebels.png",
  "usc-trojans": "/logos/teams/ncaa-usc-trojans.png",
  "utah-state-aggies": "/logos/teams/ncaa-utah-state-aggies.png",
  "utah-utes": "/logos/teams/ncaa-utah-utes.png",
  "vanderbilt-commodores": "/logos/teams/ncaa-vanderbilt-commodores.png",
  "virginia-cavaliers": "/logos/teams/ncaa-virginia-cavaliers.png",
  "virginia-tech-hokies": "/logos/teams/ncaa-virginia-tech-hokies.png",
  "wake-forest-demon-deacons": "/logos/teams/ncaa-wake-forest-demon-deacons.png",
  "washington-huskies": "/logos/teams/ncaa-washington-huskies.png",
  "washington-state-cougars": "/logos/teams/ncaa-washington-state-cougars.png",
  "west-virginia-mountaineers": "/logos/teams/ncaa-west-virginia-mountaineers.png",
  "wisconsin-badgers": "/logos/teams/ncaa-wisconsin-badgers.png",

  // College football conferences — filter-page logos for /stories?team=<conference>.
  "sec": "/logos/leagues/ncaa-conf-sec.png",
  "big-ten": "/logos/leagues/ncaa-conf-big-ten.png",
  "acc": "/logos/leagues/ncaa-conf-acc.png",
  "big-12": "/logos/leagues/ncaa-conf-big-12.png",
  "pac-12": "/logos/leagues/ncaa-conf-pac-12.png",
  "american-conference": "/logos/leagues/ncaa-conf-american-conference.png",
  "mountain-west": "/logos/leagues/ncaa-conf-mountain-west.png",
  "sun-belt": "/logos/leagues/ncaa-conf-sun-belt.png",
  "mac": "/logos/leagues/ncaa-conf-mac.png",
  "conference-usa": "/logos/leagues/ncaa-conf-conference-usa.png",
  "fbs-independents": "/logos/leagues/ncaa-conf-fbs-independents.png",
};

export const LEAGUE_LOGOS: Record<string, string> = {
  nfl: "/logos/leagues/nfl.png",
  nba: "/logos/leagues/nba.png",
  mlb: "/logos/leagues/mlb.png",
  nhl: "/logos/leagues/nhl.png",
  soccer: "/logos/leagues/soccer-ball.svg",
  f1: "/logos/leagues/racing-f1.png",
  nascar: "/logos/leagues/racing-nascar.png",
};

// Display names for every league slug used in post frontmatter. Single source of
// truth: the /stories heading and the filter page's <title> both read from here,
// so renaming a league (e.g. "Soccer" -> "Soccer/Fútbol") is a one-line change.
export const LEAGUE_NAMES: Record<string, string> = {
  nfl: "NFL",
  nba: "NBA",
  mlb: "MLB",
  nhl: "NHL",
  f1: "F1",
  soccer: "Soccer/Fútbol",
  cricket: "Cricket",
  rugby: "Rugby",
  nascar: "NASCAR",
  college: "College Football",
  cbb: "College Basketball",
  ufl: "UFL",
};

// Soccer competitions + racing series shown in the nav dropdowns.
export const COMPETITION_LOGOS: Record<string, string> = {
  // Drawn in-house. FIFA's published IP guidelines carve "incorporation into
  // the overall design, look and feel of a website" out of editorial use, and a
  // nav row on every page is precisely that, so their mark stays off the chrome.
  "International Competitions": "/logos/leagues/international-globe.svg",
  "UEFA Champions League": "/logos/leagues/soccer-uefa-champions-league.png",
  "Premier League": "/logos/leagues/soccer-premier-league.png",
  "La Liga": "/logos/leagues/soccer-la-liga.png",
  "Serie A": "/logos/leagues/soccer-serie-a.png",
  "Bundesliga": "/logos/leagues/soccer-bundesliga.png",
  "Ligue 1": "/logos/leagues/soccer-ligue-1.png",
  "MLS": "/logos/leagues/soccer-mls.png",
  // F1 constructors, from Formula 1's own media CDN.
  "Alpine": "/logos/leagues/racing-alpine.png",
  "Aston Martin": "/logos/leagues/racing-aston-martin.png",
  "Ferrari": "/logos/leagues/racing-ferrari.png",
  "Haas": "/logos/leagues/racing-haas.png",
  "McLaren": "/logos/leagues/racing-mclaren.png",
  "Mercedes": "/logos/leagues/racing-mercedes.png",
  "Racing Bulls": "/logos/leagues/racing-racing-bulls.png",
  "Red Bull Racing": "/logos/leagues/racing-red-bull-racing.png",
  "Williams": "/logos/leagues/racing-williams.png",
  // The 2026 newcomers. F1's own CDN has no assets for either, so these came
  // from marks Jake supplied and were background-knocked to transparent; the
  // Cadillac one is cropped to the crest, since the wordmark under it is
  // illegible at nav size.
  "Audi": "/logos/leagues/racing-audi.png",
  "Cadillac": "/logos/leagues/racing-cadillac.png",
  // College football conferences (ESPN ncaa_conf marks, 128px). Each school
  // schedule post is tagged with its school AND its conference, the way
  // Premier League posts carry "premier-league" plus the club.
  "SEC": "/logos/leagues/ncaa-conf-sec.png",
  "Big Ten": "/logos/leagues/ncaa-conf-big-ten.png",
  "ACC": "/logos/leagues/ncaa-conf-acc.png",
  "Big 12": "/logos/leagues/ncaa-conf-big-12.png",
  "Pac-12": "/logos/leagues/ncaa-conf-pac-12.png",
  "American Conference": "/logos/leagues/ncaa-conf-american-conference.png",
  "Mountain West": "/logos/leagues/ncaa-conf-mountain-west.png",
  "Sun Belt": "/logos/leagues/ncaa-conf-sun-belt.png",
  "MAC": "/logos/leagues/ncaa-conf-mac.png",
  "Conference USA": "/logos/leagues/ncaa-conf-conference-usa.png",
  "FBS Independents": "/logos/leagues/ncaa-conf-fbs-independents.png",
};

// Canonical display name for a slug, derived from the logo maps above so the
// nav and the /stories filter can never disagree. Rebuilding a name from its
// slug ("uefa-champions-league" -> "Uefa Champions League") mangles every
// acronym, so look it up here first and only fall back to title-casing.
// Canonical team/competition slug. Periods (and "&" / apostrophes, for Texas A&M)
// are stripped, not hyphenated: without
// that, "St. Louis Cardinals" became "st.-louis-cardinals" in the nav while every
// post tagged it "st-louis-cardinals", so both St. Louis clubs filtered to zero
// stories. Every place that turns a display name into a ?team= slug must use this.
export const teamSlug = (name: string) =>
  name.toLowerCase().replace(/[.&']/g, "").replace(/\s+/g, "-");

const slugify = teamSlug;

export const DISPLAY_NAME_BY_SLUG: Record<string, string> = Object.fromEntries(
  [...Object.keys(TEAM_LOGOS), ...Object.keys(COMPETITION_LOGOS)].map((name) => [slugify(name), name])
);

export function displayNameForSlug(slug: string): string {
  return (
    DISPLAY_NAME_BY_SLUG[slug] ??
    slug.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")
  );
}
