// Team + league logo maps, shared by the nav Header and the /stories listing pages.
// Generated from ESPN team logos (public/logos/teams). Do not hand-edit; regenerate.

export const TEAM_LOGOS: Record<string, string> = {
  "Arizona Cardinals": "/logos/teams/nfl-arizona-cardinals.png",
  "Atlanta Falcons": "/logos/teams/nfl-atlanta-falcons.png",
  "Baltimore Ravens": "/logos/teams/nfl-baltimore-ravens.png",
  "Buffalo Bills": "/logos/teams/nfl-buffalo-bills.png",
  "Carolina Panthers": "/logos/teams/nfl-carolina-panthers.png",
  "Chicago Bears": "/logos/teams/nfl-chicago-bears.png",
  "Cincinnati Bengals": "/logos/teams/nfl-cincinnati-bengals.png",
  "Cleveland Browns": "/logos/teams/nfl-cleveland-browns.png",
  "Dallas Cowboys": "/logos/teams/nfl-dallas-cowboys.png",
  "Denver Broncos": "/logos/teams/nfl-denver-broncos.png",
  "Detroit Lions": "/logos/teams/nfl-detroit-lions.png",
  "Green Bay Packers": "/logos/teams/nfl-green-bay-packers.png",
  "Houston Texans": "/logos/teams/nfl-houston-texans.png",
  "Indianapolis Colts": "/logos/teams/nfl-indianapolis-colts.png",
  "Jacksonville Jaguars": "/logos/teams/nfl-jacksonville-jaguars.png",
  "Kansas City Chiefs": "/logos/teams/nfl-kansas-city-chiefs.png",
  "Las Vegas Raiders": "/logos/teams/nfl-las-vegas-raiders.png",
  "Los Angeles Chargers": "/logos/teams/nfl-los-angeles-chargers.png",
  "Los Angeles Rams": "/logos/teams/nfl-los-angeles-rams.png",
  "Miami Dolphins": "/logos/teams/nfl-miami-dolphins.png",
  "Minnesota Vikings": "/logos/teams/nfl-minnesota-vikings.png",
  "New England Patriots": "/logos/teams/nfl-new-england-patriots.png",
  "New Orleans Saints": "/logos/teams/nfl-new-orleans-saints.png",
  "New York Giants": "/logos/teams/nfl-new-york-giants.png",
  "New York Jets": "/logos/teams/nfl-new-york-jets.png",
  "Philadelphia Eagles": "/logos/teams/nfl-philadelphia-eagles.png",
  "Pittsburgh Steelers": "/logos/teams/nfl-pittsburgh-steelers.png",
  "San Francisco 49ers": "/logos/teams/nfl-san-francisco-49ers.png",
  "Seattle Seahawks": "/logos/teams/nfl-seattle-seahawks.png",
  "Tampa Bay Buccaneers": "/logos/teams/nfl-tampa-bay-buccaneers.png",
  "Tennessee Titans": "/logos/teams/nfl-tennessee-titans.png",
  "Washington Commanders": "/logos/teams/nfl-washington-commanders.png",
  "Atlanta Hawks": "/logos/teams/nba-atlanta-hawks.png",
  "Boston Celtics": "/logos/teams/nba-boston-celtics.png",
  "Brooklyn Nets": "/logos/teams/nba-brooklyn-nets.png",
  "Charlotte Hornets": "/logos/teams/nba-charlotte-hornets.png",
  "Chicago Bulls": "/logos/teams/nba-chicago-bulls.png",
  "Cleveland Cavaliers": "/logos/teams/nba-cleveland-cavaliers.png",
  "Dallas Mavericks": "/logos/teams/nba-dallas-mavericks.png",
  "Denver Nuggets": "/logos/teams/nba-denver-nuggets.png",
  "Detroit Pistons": "/logos/teams/nba-detroit-pistons.png",
  "Golden State Warriors": "/logos/teams/nba-golden-state-warriors.png",
  "Houston Rockets": "/logos/teams/nba-houston-rockets.png",
  "Indiana Pacers": "/logos/teams/nba-indiana-pacers.png",
  "LA Clippers": "/logos/teams/nba-la-clippers.png",
  "Los Angeles Lakers": "/logos/teams/nba-los-angeles-lakers.png",
  "Memphis Grizzlies": "/logos/teams/nba-memphis-grizzlies.png",
  "Miami Heat": "/logos/teams/nba-miami-heat.png",
  "Milwaukee Bucks": "/logos/teams/nba-milwaukee-bucks.png",
  "Minnesota Timberwolves": "/logos/teams/nba-minnesota-timberwolves.png",
  "New Orleans Pelicans": "/logos/teams/nba-new-orleans-pelicans.png",
  "New York Knicks": "/logos/teams/nba-new-york-knicks.png",
  "Oklahoma City Thunder": "/logos/teams/nba-oklahoma-city-thunder.png",
  "Orlando Magic": "/logos/teams/nba-orlando-magic.png",
  "Philadelphia 76ers": "/logos/teams/nba-philadelphia-76ers.png",
  "Phoenix Suns": "/logos/teams/nba-phoenix-suns.png",
  "Portland Trail Blazers": "/logos/teams/nba-portland-trail-blazers.png",
  "Sacramento Kings": "/logos/teams/nba-sacramento-kings.png",
  "San Antonio Spurs": "/logos/teams/nba-san-antonio-spurs.png",
  "Toronto Raptors": "/logos/teams/nba-toronto-raptors.png",
  "Utah Jazz": "/logos/teams/nba-utah-jazz.png",
  "Washington Wizards": "/logos/teams/nba-washington-wizards.png",
  "Arizona Diamondbacks": "/logos/teams/mlb-arizona-diamondbacks.png",
  "Atlanta Braves": "/logos/teams/mlb-atlanta-braves.png",
  "Baltimore Orioles": "/logos/teams/mlb-baltimore-orioles.png",
  "Boston Red Sox": "/logos/teams/mlb-boston-red-sox.png",
  "Chicago Cubs": "/logos/teams/mlb-chicago-cubs.png",
  "Chicago White Sox": "/logos/teams/mlb-chicago-white-sox.png",
  "Cincinnati Reds": "/logos/teams/mlb-cincinnati-reds.png",
  "Cleveland Guardians": "/logos/teams/mlb-cleveland-guardians.png",
  "Colorado Rockies": "/logos/teams/mlb-colorado-rockies.png",
  "Detroit Tigers": "/logos/teams/mlb-detroit-tigers.png",
  "Houston Astros": "/logos/teams/mlb-houston-astros.png",
  "Kansas City Royals": "/logos/teams/mlb-kansas-city-royals.png",
  "Los Angeles Angels": "/logos/teams/mlb-los-angeles-angels.png",
  "Los Angeles Dodgers": "/logos/teams/mlb-los-angeles-dodgers.png",
  "Miami Marlins": "/logos/teams/mlb-miami-marlins.png",
  "Milwaukee Brewers": "/logos/teams/mlb-milwaukee-brewers.png",
  "Minnesota Twins": "/logos/teams/mlb-minnesota-twins.png",
  "New York Mets": "/logos/teams/mlb-new-york-mets.png",
  "New York Yankees": "/logos/teams/mlb-new-york-yankees.png",
  "Athletics": "/logos/teams/mlb-oakland-athletics.png",
  "Philadelphia Phillies": "/logos/teams/mlb-philadelphia-phillies.png",
  "Pittsburgh Pirates": "/logos/teams/mlb-pittsburgh-pirates.png",
  "San Diego Padres": "/logos/teams/mlb-san-diego-padres.png",
  "San Francisco Giants": "/logos/teams/mlb-san-francisco-giants.png",
  "Seattle Mariners": "/logos/teams/mlb-seattle-mariners.png",
  "St. Louis Cardinals": "/logos/teams/mlb-st-louis-cardinals.png",
  "Tampa Bay Rays": "/logos/teams/mlb-tampa-bay-rays.png",
  "Texas Rangers": "/logos/teams/mlb-texas-rangers.png",
  "Toronto Blue Jays": "/logos/teams/mlb-toronto-blue-jays.png",
  "Washington Nationals": "/logos/teams/mlb-washington-nationals.png",
  "Anaheim Ducks": "/logos/teams/nhl-anaheim-ducks.png",
  "Boston Bruins": "/logos/teams/nhl-boston-bruins.png",
  "Buffalo Sabres": "/logos/teams/nhl-buffalo-sabres.png",
  "Calgary Flames": "/logos/teams/nhl-calgary-flames.png",
  "Carolina Hurricanes": "/logos/teams/nhl-carolina-hurricanes.png",
  "Chicago Blackhawks": "/logos/teams/nhl-chicago-blackhawks.png",
  "Colorado Avalanche": "/logos/teams/nhl-colorado-avalanche.png",
  "Columbus Blue Jackets": "/logos/teams/nhl-columbus-blue-jackets.png",
  "Dallas Stars": "/logos/teams/nhl-dallas-stars.png",
  "Detroit Red Wings": "/logos/teams/nhl-detroit-red-wings.png",
  "Edmonton Oilers": "/logos/teams/nhl-edmonton-oilers.png",
  "Florida Panthers": "/logos/teams/nhl-florida-panthers.png",
  "Los Angeles Kings": "/logos/teams/nhl-los-angeles-kings.png",
  "Minnesota Wild": "/logos/teams/nhl-minnesota-wild.png",
  "Montreal Canadiens": "/logos/teams/nhl-montreal-canadiens.png",
  "Nashville Predators": "/logos/teams/nhl-nashville-predators.png",
  "New Jersey Devils": "/logos/teams/nhl-new-jersey-devils.png",
  "New York Islanders": "/logos/teams/nhl-new-york-islanders.png",
  "New York Rangers": "/logos/teams/nhl-new-york-rangers.png",
  "Ottawa Senators": "/logos/teams/nhl-ottawa-senators.png",
  "Philadelphia Flyers": "/logos/teams/nhl-philadelphia-flyers.png",
  "Pittsburgh Penguins": "/logos/teams/nhl-pittsburgh-penguins.png",
  "San Jose Sharks": "/logos/teams/nhl-san-jose-sharks.png",
  "Seattle Kraken": "/logos/teams/nhl-seattle-kraken.png",
  "St. Louis Blues": "/logos/teams/nhl-st-louis-blues.png",
  "Tampa Bay Lightning": "/logos/teams/nhl-tampa-bay-lightning.png",
  "Toronto Maple Leafs": "/logos/teams/nhl-toronto-maple-leafs.png",
  "Utah Hockey Club": "/logos/teams/nhl-utah-hockey-club.png",
  "Vancouver Canucks": "/logos/teams/nhl-vancouver-canucks.png",
  "Vegas Golden Knights": "/logos/teams/nhl-vegas-golden-knights.png",
  "Washington Capitals": "/logos/teams/nhl-washington-capitals.png",
  "Winnipeg Jets": "/logos/teams/nhl-winnipeg-jets.png",
};

// Keyed by the URL slug the nav builds (name.toLowerCase().replace(/\\s+/g, '-')),
// so the /stories?team=<slug> page can look a logo up from the query param.
export const TEAM_LOGO_BY_SLUG: Record<string, string> = {
  // Soccer competitions + F1 constructors — filter-page logos for /stories?team=<slug>.
  // The nav shows these via COMPETITION_LOGOS (by display name); this maps the slug the
  // nav builds so the filter heading gets the same logo. Assets in /logos/leagues/.
  "international-competitions": "/logos/leagues/international-globe.svg",
  "uefa-champions-league": "/logos/leagues/soccer-uefa-champions-league.png",
  "premier-league": "/logos/leagues/soccer-premier-league.png",
  "la-liga": "/logos/leagues/soccer-la-liga.png",
  "serie-a": "/logos/leagues/soccer-serie-a.png",
  "bundesliga": "/logos/leagues/soccer-bundesliga.png",
  "ligue-1": "/logos/leagues/soccer-ligue-1.png",
  "mls": "/logos/leagues/soccer-mls.png",
  "alpine": "/logos/leagues/racing-alpine.png",
  "aston-martin": "/logos/leagues/racing-aston-martin.png",
  "audi": "/logos/leagues/racing-audi.png",
  "cadillac": "/logos/leagues/racing-cadillac.png",
  "ferrari": "/logos/leagues/racing-ferrari.png",
  "haas": "/logos/leagues/racing-haas.png",
  "mclaren": "/logos/leagues/racing-mclaren.png",
  "mercedes": "/logos/leagues/racing-mercedes.png",
  "racing-bulls": "/logos/leagues/racing-racing-bulls.png",
  "red-bull-racing": "/logos/leagues/racing-red-bull-racing.png",
  "williams": "/logos/leagues/racing-williams.png",
  "arizona-cardinals": "/logos/teams/nfl-arizona-cardinals.png",
  "atlanta-falcons": "/logos/teams/nfl-atlanta-falcons.png",
  "baltimore-ravens": "/logos/teams/nfl-baltimore-ravens.png",
  "buffalo-bills": "/logos/teams/nfl-buffalo-bills.png",
  "carolina-panthers": "/logos/teams/nfl-carolina-panthers.png",
  "chicago-bears": "/logos/teams/nfl-chicago-bears.png",
  "cincinnati-bengals": "/logos/teams/nfl-cincinnati-bengals.png",
  "cleveland-browns": "/logos/teams/nfl-cleveland-browns.png",
  "dallas-cowboys": "/logos/teams/nfl-dallas-cowboys.png",
  "denver-broncos": "/logos/teams/nfl-denver-broncos.png",
  "detroit-lions": "/logos/teams/nfl-detroit-lions.png",
  "green-bay-packers": "/logos/teams/nfl-green-bay-packers.png",
  "houston-texans": "/logos/teams/nfl-houston-texans.png",
  "indianapolis-colts": "/logos/teams/nfl-indianapolis-colts.png",
  "jacksonville-jaguars": "/logos/teams/nfl-jacksonville-jaguars.png",
  "kansas-city-chiefs": "/logos/teams/nfl-kansas-city-chiefs.png",
  "las-vegas-raiders": "/logos/teams/nfl-las-vegas-raiders.png",
  "los-angeles-chargers": "/logos/teams/nfl-los-angeles-chargers.png",
  "los-angeles-rams": "/logos/teams/nfl-los-angeles-rams.png",
  "miami-dolphins": "/logos/teams/nfl-miami-dolphins.png",
  "minnesota-vikings": "/logos/teams/nfl-minnesota-vikings.png",
  "new-england-patriots": "/logos/teams/nfl-new-england-patriots.png",
  "new-orleans-saints": "/logos/teams/nfl-new-orleans-saints.png",
  "new-york-giants": "/logos/teams/nfl-new-york-giants.png",
  "new-york-jets": "/logos/teams/nfl-new-york-jets.png",
  "philadelphia-eagles": "/logos/teams/nfl-philadelphia-eagles.png",
  "pittsburgh-steelers": "/logos/teams/nfl-pittsburgh-steelers.png",
  "san-francisco-49ers": "/logos/teams/nfl-san-francisco-49ers.png",
  "seattle-seahawks": "/logos/teams/nfl-seattle-seahawks.png",
  "tampa-bay-buccaneers": "/logos/teams/nfl-tampa-bay-buccaneers.png",
  "tennessee-titans": "/logos/teams/nfl-tennessee-titans.png",
  "washington-commanders": "/logos/teams/nfl-washington-commanders.png",
  "atlanta-hawks": "/logos/teams/nba-atlanta-hawks.png",
  "boston-celtics": "/logos/teams/nba-boston-celtics.png",
  "brooklyn-nets": "/logos/teams/nba-brooklyn-nets.png",
  "charlotte-hornets": "/logos/teams/nba-charlotte-hornets.png",
  "chicago-bulls": "/logos/teams/nba-chicago-bulls.png",
  "cleveland-cavaliers": "/logos/teams/nba-cleveland-cavaliers.png",
  "dallas-mavericks": "/logos/teams/nba-dallas-mavericks.png",
  "denver-nuggets": "/logos/teams/nba-denver-nuggets.png",
  "detroit-pistons": "/logos/teams/nba-detroit-pistons.png",
  "golden-state-warriors": "/logos/teams/nba-golden-state-warriors.png",
  "houston-rockets": "/logos/teams/nba-houston-rockets.png",
  "indiana-pacers": "/logos/teams/nba-indiana-pacers.png",
  "la-clippers": "/logos/teams/nba-la-clippers.png",
  "los-angeles-lakers": "/logos/teams/nba-los-angeles-lakers.png",
  "memphis-grizzlies": "/logos/teams/nba-memphis-grizzlies.png",
  "miami-heat": "/logos/teams/nba-miami-heat.png",
  "milwaukee-bucks": "/logos/teams/nba-milwaukee-bucks.png",
  "minnesota-timberwolves": "/logos/teams/nba-minnesota-timberwolves.png",
  "new-orleans-pelicans": "/logos/teams/nba-new-orleans-pelicans.png",
  "new-york-knicks": "/logos/teams/nba-new-york-knicks.png",
  "oklahoma-city-thunder": "/logos/teams/nba-oklahoma-city-thunder.png",
  "orlando-magic": "/logos/teams/nba-orlando-magic.png",
  "philadelphia-76ers": "/logos/teams/nba-philadelphia-76ers.png",
  "phoenix-suns": "/logos/teams/nba-phoenix-suns.png",
  "portland-trail-blazers": "/logos/teams/nba-portland-trail-blazers.png",
  "sacramento-kings": "/logos/teams/nba-sacramento-kings.png",
  "san-antonio-spurs": "/logos/teams/nba-san-antonio-spurs.png",
  "toronto-raptors": "/logos/teams/nba-toronto-raptors.png",
  "utah-jazz": "/logos/teams/nba-utah-jazz.png",
  "washington-wizards": "/logos/teams/nba-washington-wizards.png",
  "arizona-diamondbacks": "/logos/teams/mlb-arizona-diamondbacks.png",
  "atlanta-braves": "/logos/teams/mlb-atlanta-braves.png",
  "baltimore-orioles": "/logos/teams/mlb-baltimore-orioles.png",
  "boston-red-sox": "/logos/teams/mlb-boston-red-sox.png",
  "chicago-cubs": "/logos/teams/mlb-chicago-cubs.png",
  "chicago-white-sox": "/logos/teams/mlb-chicago-white-sox.png",
  "cincinnati-reds": "/logos/teams/mlb-cincinnati-reds.png",
  "cleveland-guardians": "/logos/teams/mlb-cleveland-guardians.png",
  "colorado-rockies": "/logos/teams/mlb-colorado-rockies.png",
  "detroit-tigers": "/logos/teams/mlb-detroit-tigers.png",
  "houston-astros": "/logos/teams/mlb-houston-astros.png",
  "kansas-city-royals": "/logos/teams/mlb-kansas-city-royals.png",
  "los-angeles-angels": "/logos/teams/mlb-los-angeles-angels.png",
  "los-angeles-dodgers": "/logos/teams/mlb-los-angeles-dodgers.png",
  "miami-marlins": "/logos/teams/mlb-miami-marlins.png",
  "milwaukee-brewers": "/logos/teams/mlb-milwaukee-brewers.png",
  "minnesota-twins": "/logos/teams/mlb-minnesota-twins.png",
  "new-york-mets": "/logos/teams/mlb-new-york-mets.png",
  "new-york-yankees": "/logos/teams/mlb-new-york-yankees.png",
  "athletics": "/logos/teams/mlb-oakland-athletics.png",
  // Legacy slug: kept so older "oakland-athletics" links still resolve a logo.
  "oakland-athletics": "/logos/teams/mlb-oakland-athletics.png",
  "philadelphia-phillies": "/logos/teams/mlb-philadelphia-phillies.png",
  "pittsburgh-pirates": "/logos/teams/mlb-pittsburgh-pirates.png",
  "san-diego-padres": "/logos/teams/mlb-san-diego-padres.png",
  "san-francisco-giants": "/logos/teams/mlb-san-francisco-giants.png",
  "seattle-mariners": "/logos/teams/mlb-seattle-mariners.png",
  "st-louis-cardinals": "/logos/teams/mlb-st-louis-cardinals.png",
  "tampa-bay-rays": "/logos/teams/mlb-tampa-bay-rays.png",
  "texas-rangers": "/logos/teams/mlb-texas-rangers.png",
  "toronto-blue-jays": "/logos/teams/mlb-toronto-blue-jays.png",
  "washington-nationals": "/logos/teams/mlb-washington-nationals.png",
  "anaheim-ducks": "/logos/teams/nhl-anaheim-ducks.png",
  "boston-bruins": "/logos/teams/nhl-boston-bruins.png",
  "buffalo-sabres": "/logos/teams/nhl-buffalo-sabres.png",
  "calgary-flames": "/logos/teams/nhl-calgary-flames.png",
  "carolina-hurricanes": "/logos/teams/nhl-carolina-hurricanes.png",
  "chicago-blackhawks": "/logos/teams/nhl-chicago-blackhawks.png",
  "colorado-avalanche": "/logos/teams/nhl-colorado-avalanche.png",
  "columbus-blue-jackets": "/logos/teams/nhl-columbus-blue-jackets.png",
  "dallas-stars": "/logos/teams/nhl-dallas-stars.png",
  "detroit-red-wings": "/logos/teams/nhl-detroit-red-wings.png",
  "edmonton-oilers": "/logos/teams/nhl-edmonton-oilers.png",
  "florida-panthers": "/logos/teams/nhl-florida-panthers.png",
  "los-angeles-kings": "/logos/teams/nhl-los-angeles-kings.png",
  "minnesota-wild": "/logos/teams/nhl-minnesota-wild.png",
  "montreal-canadiens": "/logos/teams/nhl-montreal-canadiens.png",
  "nashville-predators": "/logos/teams/nhl-nashville-predators.png",
  "new-jersey-devils": "/logos/teams/nhl-new-jersey-devils.png",
  "new-york-islanders": "/logos/teams/nhl-new-york-islanders.png",
  "new-york-rangers": "/logos/teams/nhl-new-york-rangers.png",
  "ottawa-senators": "/logos/teams/nhl-ottawa-senators.png",
  "philadelphia-flyers": "/logos/teams/nhl-philadelphia-flyers.png",
  "pittsburgh-penguins": "/logos/teams/nhl-pittsburgh-penguins.png",
  "san-jose-sharks": "/logos/teams/nhl-san-jose-sharks.png",
  "seattle-kraken": "/logos/teams/nhl-seattle-kraken.png",
  "st-louis-blues": "/logos/teams/nhl-st-louis-blues.png",
  "tampa-bay-lightning": "/logos/teams/nhl-tampa-bay-lightning.png",
  "toronto-maple-leafs": "/logos/teams/nhl-toronto-maple-leafs.png",
  "utah-hockey-club": "/logos/teams/nhl-utah-hockey-club.png",
  "vancouver-canucks": "/logos/teams/nhl-vancouver-canucks.png",
  "vegas-golden-knights": "/logos/teams/nhl-vegas-golden-knights.png",
  "washington-capitals": "/logos/teams/nhl-washington-capitals.png",
  "winnipeg-jets": "/logos/teams/nhl-winnipeg-jets.png",
};

export const LEAGUE_LOGOS: Record<string, string> = {
  nfl: "/logos/leagues/nfl.png",
  nba: "/logos/leagues/nba.png",
  mlb: "/logos/leagues/mlb.png",
  nhl: "/logos/leagues/nhl.png",
  soccer: "/logos/leagues/soccer-ball.svg",
  f1: "/logos/leagues/racing-f1.png",
  nascar: "/logos/leagues/racing-nascar.png",
};

// Display names for every league slug used in post frontmatter. Single source of
// truth: the /stories heading and the filter page's <title> both read from here,
// so renaming a league (e.g. "Soccer" -> "Soccer/Fútbol") is a one-line change.
export const LEAGUE_NAMES: Record<string, string> = {
  nfl: "NFL",
  nba: "NBA",
  mlb: "MLB",
  nhl: "NHL",
  f1: "F1",
  soccer: "Soccer/Fútbol",
  cricket: "Cricket",
  rugby: "Rugby",
  nascar: "NASCAR",
  college: "College",
  ufl: "UFL",
};

// Soccer competitions + racing series shown in the nav dropdowns.
export const COMPETITION_LOGOS: Record<string, string> = {
  // Drawn in-house. FIFA's published IP guidelines carve "incorporation into
  // the overall design, look and feel of a website" out of editorial use, and a
  // nav row on every page is precisely that, so their mark stays off the chrome.
  "International Competitions": "/logos/leagues/international-globe.svg",
  "UEFA Champions League": "/logos/leagues/soccer-uefa-champions-league.png",
  "Premier League": "/logos/leagues/soccer-premier-league.png",
  "La Liga": "/logos/leagues/soccer-la-liga.png",
  "Serie A": "/logos/leagues/soccer-serie-a.png",
  "Bundesliga": "/logos/leagues/soccer-bundesliga.png",
  "Ligue 1": "/logos/leagues/soccer-ligue-1.png",
  "MLS": "/logos/leagues/soccer-mls.png",
  // F1 constructors, from Formula 1's own media CDN.
  "Alpine": "/logos/leagues/racing-alpine.png",
  "Aston Martin": "/logos/leagues/racing-aston-martin.png",
  "Ferrari": "/logos/leagues/racing-ferrari.png",
  "Haas": "/logos/leagues/racing-haas.png",
  "McLaren": "/logos/leagues/racing-mclaren.png",
  "Mercedes": "/logos/leagues/racing-mercedes.png",
  "Racing Bulls": "/logos/leagues/racing-racing-bulls.png",
  "Red Bull Racing": "/logos/leagues/racing-red-bull-racing.png",
  "Williams": "/logos/leagues/racing-williams.png",
  // The 2026 newcomers. F1's own CDN has no assets for either, so these came
  // from marks Jake supplied and were background-knocked to transparent; the
  // Cadillac one is cropped to the crest, since the wordmark under it is
  // illegible at nav size.
  "Audi": "/logos/leagues/racing-audi.png",
  "Cadillac": "/logos/leagues/racing-cadillac.png",
};

// Canonical display name for a slug, derived from the logo maps above so the
// nav and the /stories filter can never disagree. Rebuilding a name from its
// slug ("uefa-champions-league" -> "Uefa Champions League") mangles every
// acronym, so look it up here first and only fall back to title-casing.
// Canonical team/competition slug. Periods are stripped, not hyphenated: without
// that, "St. Louis Cardinals" became "st.-louis-cardinals" in the nav while every
// post tagged it "st-louis-cardinals", so both St. Louis clubs filtered to zero
// stories. Every place that turns a display name into a ?team= slug must use this.
export const teamSlug = (name: string) =>
  name.toLowerCase().replace(/\./g, "").replace(/\s+/g, "-");

const slugify = teamSlug;

export const DISPLAY_NAME_BY_SLUG: Record<string, string> = Object.fromEntries(
  [...Object.keys(TEAM_LOGOS), ...Object.keys(COMPETITION_LOGOS)].map((name) => [slugify(name), name])
);

export function displayNameForSlug(slug: string): string {
  return (
    DISPLAY_NAME_BY_SLUG[slug] ??
    slug.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")
  );
}
